
[[dependencies]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3"

[[dependencies]]
  name = "github.com/gorialla/sessions"
  version = "1.1"

[[dependencies]]
  name = "github.com/gorilla/mux"
  version = "1.3"

[[dependencies]]
  name = "github.com/jinzhu/gorm"
  version = "1.0"
